---
in:
  type: postgresql
  host: localhost
  user: germana.a.queiroz
  password: 1234
  database: northwind
  query: |
    SELECT * FROM mytable
out:
  type: file
  path_prefix: C:\\Users\\germana.a.queiroz\\Challenge_1007\\
    LH_ED_GERMANA_A_QUEIROZ\\data\\postregressql_orders_data.sql
  file_ext: \postregressql_orders_data.sql
